### ISSUE TITLE
Using by Dynamic Action: Change or Before Page Submit, not working

### ISSUE THREAD

**Issue by igorsala7** [nbuytaert1/apex-alertify#3]
Hello fabien-d!

Thank you for your work on this plugin. It's very, very helpful!

I'm having some trouble only to use in case of dynamic action on change item and before page submit, doesn't show the confirm alert. If helps, if I add a true action of Alert (Apex native action), before the Alertify [Plugin] action, its works normally, but if I only add the Alertify [Plugin] action alone, doesn't work.

Thank you.

**Comment by igorsala7** [comment]
Interesting. I put an initial value ' ' in the field wich I add the Dynamic Action, at the time the page is loaded and it worked. But I'm putting the message as a field & P1_MESSAGE. if the value of p1_message change does not alter the message, maintains the value ' ' .

**Comment by nbuytaert1** [comment]
The help text for the "Message" attribute of the Alertify plugin states:

> The following substitution syntax is available:
>* Static substitution: replaces a placeholder during rendering of the page - e.g. &P30_PROMPT_RESULT.
>* Dynamic substitution: replaces a placeholder with the current value of the browser - e.g. #P30_PROMPT_RESULT#

The ampersand syntax gets an item's value from session state. The hashtag syntax gets the item's value using JavaScript. So in your case, use #P1_MESSAGE# instead of &P1_MESSAGE. and the confirm message should work as expected.

Hope that helps,
Nick
